name: Run tests and deploy

# Run this workflow whene something new is pushed
on: push

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  # deploy:
  #   needs: run-tests
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: testing connection to Ocean Droplet
  #       uses: appleboy/ssh-action@v0.1.4
  #       with:
  #         host: ${{ secrets.DIGITAL_OCEAN_IP_ADRESS }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.PRIVATE_KEY }}
  #         port: ${{ secrets.PORT }}
  #         script: |
  #           cd ~/my-project
  #           echo 'cd to my-project'
  #           git pull origin master
  #           echo 'Repository has been pulled'
  #           systemctl restart my-project
  #           echo 'my-project rebooted'
  #           git status
  

